# Generated by Django 4.1.2 on 2022-11-17 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ques_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question', models.CharField(default='', max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='user_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Usertype', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='reg_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='', max_length=50)),
                ('Dob', models.CharField(default='', max_length=50)),
                ('Gender', models.CharField(default='', max_length=50)),
                ('Mobileno', models.CharField(default='', max_length=50)),
                ('Email', models.CharField(default='', max_length=50, unique=True)),
                ('Address', models.CharField(default='', max_length=50)),
                ('Password', models.CharField(default='', max_length=50)),
                ('Status', models.CharField(default='Approve', max_length=50)),
                ('Usertype', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mediapp.user_type')),
            ],
        ),
    ]
