# Generated by Django 4.1.2 on 2022-11-17 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reg_tbl',
            name='Status',
            field=models.CharField(default='', max_length=50),
        ),
    ]
