# Generated by Django 4.1.2 on 2022-11-21 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mediapp', '0003_ques_tbl_replay_ques_tbl_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ques_tbl',
            name='Usertype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mediapp.user_type'),
        ),
    ]
