# Generated by Django 4.1.2 on 2022-11-21 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediapp', '0004_ques_tbl_usertype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ques_tbl',
            name='Usertype',
        ),
        migrations.AddField(
            model_name='ques_tbl',
            name='did',
            field=models.CharField(default='', max_length=50),
        ),
    ]
