# Generated by Django 4.1.2 on 2022-11-21 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mediapp', '0005_remove_ques_tbl_usertype_ques_tbl_did'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ques_tbl',
            old_name='did',
            new_name='uid',
        ),
    ]
