# Generated by Django 4.1.2 on 2022-11-21 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediapp', '0006_rename_did_ques_tbl_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ques_tbl',
            name='uid',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
