# Generated by Django 4.1.2 on 2022-11-21 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mediapp', '0007_alter_ques_tbl_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ques_tbl',
            name='uid',
        ),
        migrations.AddField(
            model_name='ques_tbl',
            name='Usertype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mediapp.user_type'),
        ),
    ]
