# Generated by Django 4.1.2 on 2022-11-22 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mediapp', '0009_remove_ques_tbl_usertype_ques_tbl_did'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ques_tbl',
            name='did',
        ),
        migrations.AddField(
            model_name='ques_tbl',
            name='Usertype_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mediapp.reg_tbl'),
        ),
    ]
