# Generated by Django 4.1.2 on 2022-11-22 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediapp', '0010_remove_ques_tbl_did_ques_tbl_usertype_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ques_tbl',
            name='Usertype_id',
        ),
        migrations.AddField(
            model_name='ques_tbl',
            name='did',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
