# Generated by Django 4.1.2 on 2022-11-23 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mediapp', '0013_alter_ques_tbl_did'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ques_tbl',
            name='did',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mediapp.reg_tbl'),
        ),
    ]
