# Generated by Django 4.1.2 on 2022-11-23 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mediapp', '0015_ans_tbl'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ans_tbl',
            old_name='Replay',
            new_name='Answer',
        ),
    ]
