# Generated by Django 4.1.2 on 2022-11-23 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mediapp', '0016_rename_replay_ans_tbl_answer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ans_tbl',
        ),
    ]
