# Generated by Django 4.1.2 on 2022-11-23 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mediapp', '0017_delete_ans_tbl'),
    ]

    operations = [
        migrations.CreateModel(
            name='ans_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Replay', models.CharField(default='', max_length=200, null=True)),
                ('uid', models.TextField(default='', max_length=50)),
                ('qid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mediapp.ques_tbl')),
            ],
        ),
    ]
