# Generated by Django 4.1.2 on 2022-11-23 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediapp', '0018_ans_tbl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ans_tbl',
            name='Replay',
            field=models.TextField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='ans_tbl',
            name='uid',
            field=models.TextField(default='', max_length=200),
        ),
    ]
