# Generated by Django 4.1.2 on 2022-11-26 06:17

from django.db import migrations, models
import mediapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('mediapp', '0019_alter_ans_tbl_replay_alter_ans_tbl_uid'),
    ]

    operations = [
        migrations.CreateModel(
            name='nutrition_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.TextField(default='', max_length=200)),
                ('Description', models.CharField(max_length=500, null=True)),
                ('Image', models.FileField(default='', max_length=500, upload_to=mediapp.models.nutrition1)),
                ('BP', models.TextField(default='', max_length=200)),
                ('Cholesterol', models.TextField(default='', max_length=200)),
                ('Diabetes', models.TextField(default='', max_length=200)),
                ('Weight', models.TextField(default='', max_length=200)),
                ('did', models.TextField(default='', max_length=200)),
            ],
        ),
    ]
