# Generated by Django 4.1.2 on 2022-11-30 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mediapp', '0023_rename_replay_answer_tbl_replay'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer_tbl',
            name='qid',
        ),
        migrations.RemoveField(
            model_name='answer_tbl',
            name='uid',
        ),
    ]
