# Generated by Django 4.1.2 on 2022-11-30 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mediapp', '0024_remove_answer_tbl_qid_remove_answer_tbl_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer_tbl',
            name='qid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mediapp.quest_tbl'),
        ),
        migrations.AddField(
            model_name='answer_tbl',
            name='uid',
            field=models.TextField(default='', max_length=200),
        ),
    ]
