# Generated by Django 4.1.2 on 2022-12-02 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mediapp', '0025_answer_tbl_qid_answer_tbl_uid'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='answer_tbl',
            new_name='answers_tbl',
        ),
    ]
