# Generated by Django 4.1.2 on 2022-12-02 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mediapp', '0026_rename_answer_tbl_answers_tbl'),
    ]

    operations = [
        migrations.DeleteModel(
            name='answers_tbl',
        ),
    ]
