# Generated by Django 4.1.2 on 2022-12-02 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mediapp', '0029_delete_answers_tbl'),
    ]

    operations = [
        migrations.CreateModel(
            name='answer_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('replay', models.TextField(default='', max_length=200)),
                ('uid', models.TextField(default='', max_length=200)),
                ('qid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mediapp.quest_tbl')),
            ],
        ),
    ]
