# Generated by Django 4.1.2 on 2022-12-02 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mediapp', '0030_answer_tbl'),
    ]

    operations = [
        migrations.DeleteModel(
            name='answer_tbl',
        ),
    ]
