# Generated by Django 4.1.2 on 2022-12-05 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediapp', '0032_answer_tbl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reg_tbl',
            name='Status',
            field=models.TextField(default='', max_length=50),
        ),
    ]
