# Generated by Django 4.1.2 on 2022-12-06 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediapp', '0034_nutrition_tbl_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer_tbl',
            name='ans',
            field=models.TextField(default='', max_length=200),
        ),
    ]
